name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - macos-13
          - macos-14
        arch:
          - x86_64
          - aarch64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Build & Test
        shell: bash
        env:
          TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
          TEST_PUBLIC_KEY: ${{ secrets.TEST_PUBLIC_KEY }}
          TEST_PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          TEST_VAULT: ${{ secrets.TEST_VAULT }}
        run: |
          ./build-lib.sh
          if [[ "${{ matrix.os }}" == ubuntu* ]]; then
            export LD_LIBRARY_PATH="${GITHUB_WORKSPACE}:${LD_LIBRARY_PATH:-}"
          else
            export DYLD_LIBRARY_PATH="${GITHUB_WORKSPACE}:${DYLD_LIBRARY_PATH:-}"
          fi
          go test ./...