name: Go CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Set LD_LIBRARY_PATH
        run: export LD_LIBRARY_PATH="$(pwd):${LD_LIBRARY_PATH:-}"

      - name: Run tests
        run: go test ./...
